name: hot_rank

on:
  push:
    branches: [ master ]
  watch:
    types: started
  schedule:
    - cron: "0 23 * * *"

jobs:
  workflows:
    runs-on: ubuntu-latest
    steps:

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.4' # The Go version to download (if necessary) and use.
      - run: go mod download
      - run: go run generate_readme.go
      - name: Commit files
        run: |
          git add README.md
          git config --local user.email "jacktanger@163.com"
          git config --local user.name "HeCG95"
          git commit --allow-empty -m ":rocket: Update today's hot rank on $(date)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}
